import { Receipt } from "mppx";
import { afterEach, describe, expect, it } from "vitest";
import type { Address, TransactionSigner } from "@solana/kit";

import {
  airdropAndWait,
  assertRpcReady,
  createAssociatedTokenAccount,
  createMppClient,
  createSigner,
  createSplMint,
  defaultRpcUrl,
  getLamportBalance,
  getTokenBalance,
  mintSplTokensToOwner,
  splTokenDecimals,
  startExpressServer,
  waitForLamportBalanceAtLeast,
  waitForTokenBalanceAtLeast,
  waitForTransaction,
} from "./support/surfpool.js";

const rpcUrl = defaultRpcUrl;
const mppSecret = "surfpool-security-secret-with-sufficient-entropy";
const realm = "surfpool.payment-security.e2e";

let closeServers: Array<() => Promise<void>> = [];

afterEach(async () => {
  const servers = closeServers;
  closeServers = [];
  await Promise.all(servers.map((close) => close()));
});

describe("paid Express payment security on Surfpool", () => {
  it("captures the Authorization generated by the client challenge flow", async () => {
    await assertRpcReady(rpcUrl);
    const payer = await createSigner();
    const recipient = await createSigner();
    const amount = 25_000n;

    await airdropAndWait(payer.address, 1_000_000_000n, rpcUrl);
    await airdropAndWait(recipient.address, 1_000_000n, rpcUrl);
    const baseUrl = await serve(nativeEnv(recipient.address, amount));

    const paid = await payAndCaptureAuthorization(payer, `${baseUrl}/api/v1/agent-report`);
    await expectConfirmedReceiptTransaction(paid.receipt);

    expect(paid.authorization).toMatch(/^Payment /);
    expect(paid.response.status).toBe(200);
    expect(await paid.response.json()).toMatchObject({
      ok: true,
      product: "agent-report",
      settlement: "verified-by-solana-mpp",
    });
  }, 120_000);

  it("does not credit twice when the same Authorization is replayed on the same route", async () => {
    await assertRpcReady(rpcUrl);
    const payer = await createSigner();
    const recipient = await createSigner();
    const amount = 25_000n;

    await airdropAndWait(payer.address, 1_000_000_000n, rpcUrl);
    await airdropAndWait(recipient.address, 1_000_000n, rpcUrl);
    const before = await getLamportBalance(recipient.address, rpcUrl);
    const baseUrl = await serve(nativeEnv(recipient.address, amount));
    const target = `${baseUrl}/api/v1/agent-report`;

    const paid = await payAndCaptureAuthorization(payer, target);
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForLamportBalanceAtLeast(recipient.address, before + amount, rpcUrl);

    const replay = await fetch(target, {
      headers: { authorization: paid.authorization },
    });
    await delay(1_000);
    const afterReplay = await getLamportBalance(recipient.address, rpcUrl);

    expect(afterPayment - before).toBe(amount);
    expect(afterReplay).toBe(afterPayment);
    expect(replay.status).not.toBe(200);
  }, 120_000);

  it("rejects reusing Authorization on the same wallet tool request", async () => {
    await assertRpcReady(rpcUrl);
    const payer = await createSigner();
    const recipient = await createSigner();
    const inspectedWallet = await createSigner();
    const amount = 25_000n;

    await airdropAndWait(payer.address, 1_000_000_000n, rpcUrl);
    await airdropAndWait(recipient.address, 1_000_000n, rpcUrl);
    await airdropAndWait(inspectedWallet.address, 1_234_567n, rpcUrl);
    const before = await getLamportBalance(recipient.address, rpcUrl);
    const baseUrl = await serve(nativeEnv(recipient.address, amount));
    const target = `${baseUrl}/api/v1/tools/wallet-analysis`;

    const paid = await payAndCaptureAuthorization(payer, target, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ address: inspectedWallet.address }),
    });
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForLamportBalanceAtLeast(recipient.address, before + amount, rpcUrl);

    const replay = await fetch(target, {
      method: "POST",
      headers: {
        authorization: paid.authorization,
        "content-type": "application/json",
      },
      body: JSON.stringify({ address: inspectedWallet.address }),
    });
    const body = await optionalJson(replay);
    await delay(1_000);

    expect(replay.status).not.toBe(200);
    expect(body).not.toMatchObject({ ok: true, address: inspectedWallet.address });
    expect(await getLamportBalance(recipient.address, rpcUrl)).toBe(afterPayment);
  }, 120_000);

  it("rejects reusing Authorization against a different route", async () => {
    await assertRpcReady(rpcUrl);
    const payer = await createSigner();
    const recipient = await createSigner();
    const inspectedWallet = await createSigner();
    const amount = 25_000n;

    await airdropAndWait(payer.address, 1_000_000_000n, rpcUrl);
    await airdropAndWait(recipient.address, 1_000_000n, rpcUrl);
    await airdropAndWait(inspectedWallet.address, 1_234_567n, rpcUrl);
    const before = await getLamportBalance(recipient.address, rpcUrl);
    const baseUrl = await serve(nativeEnv(recipient.address, amount));

    const paid = await payAndCaptureAuthorization(payer, `${baseUrl}/api/v1/agent-report`);
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForLamportBalanceAtLeast(recipient.address, before + amount, rpcUrl);

    const replay = await fetch(`${baseUrl}/api/v1/tools/wallet-analysis`, {
      method: "POST",
      headers: {
        authorization: paid.authorization,
        "content-type": "application/json",
      },
      body: JSON.stringify({ address: inspectedWallet.address }),
    });
    const body = await optionalJson(replay);
    await delay(1_000);

    expect(replay.status).not.toBe(200);
    expect(body).not.toMatchObject({ ok: true, address: inspectedWallet.address });
    expect(await getLamportBalance(recipient.address, rpcUrl)).toBe(afterPayment);
  }, 120_000);

  it("rejects reusing Authorization against a different amount", async () => {
    await assertRpcReady(rpcUrl);
    const payer = await createSigner();
    const recipient = await createSigner();
    const amount = 25_000n;

    await airdropAndWait(payer.address, 1_000_000_000n, rpcUrl);
    await airdropAndWait(recipient.address, 1_000_000n, rpcUrl);
    const before = await getLamportBalance(recipient.address, rpcUrl);
    const firstBaseUrl = await serve(nativeEnv(recipient.address, amount));
    const secondBaseUrl = await serve(nativeEnv(recipient.address, amount + 1n));

    const paid = await payAndCaptureAuthorization(payer, `${firstBaseUrl}/api/v1/agent-report`);
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForLamportBalanceAtLeast(recipient.address, before + amount, rpcUrl);

    const replay = await fetch(`${secondBaseUrl}/api/v1/agent-report`, {
      headers: { authorization: paid.authorization },
    });
    const body = await optionalJson(replay);
    await delay(1_000);

    expect(replay.status).not.toBe(200);
    expect(body).not.toMatchObject({ ok: true, product: "agent-report" });
    expect(await getLamportBalance(recipient.address, rpcUrl)).toBe(afterPayment);
  }, 120_000);

  it("rejects reusing Authorization against a different split policy", async () => {
    await assertRpcReady(rpcUrl);
    const actors = await createSplActors(20_000_000n);
    const total = 10_000_000n;
    const firstPlatform = 1_000_000n;
    const firstReferrer = 500_000n;
    const secondPlatform = 1_500_000n;
    const secondReferrer = 250_000n;
    await Promise.all([
      createAssociatedTokenAccount({ payer: actors.payer, mint: actors.mint, owner: actors.seller.address }, rpcUrl),
      createAssociatedTokenAccount({ payer: actors.payer, mint: actors.mint, owner: actors.platform.address }, rpcUrl),
      createAssociatedTokenAccount({ payer: actors.payer, mint: actors.mint, owner: actors.referrer.address }, rpcUrl),
    ]);
    const before = await tokenBalances(actors);
    const firstBaseUrl = await serve(splEnv(actors, {
      marketplaceAmount: total,
      platformSplit: firstPlatform,
      referrerSplit: firstReferrer,
    }));
    const secondBaseUrl = await serve(splEnv(actors, {
      marketplaceAmount: total,
      platformSplit: secondPlatform,
      referrerSplit: secondReferrer,
    }));

    const paid = await payAndCaptureAuthorization(
      actors.payer,
      `${firstBaseUrl}/api/v1/marketplace/marketplace-dataset/purchase`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ idempotencyKey: "split-policy" }),
      },
    );
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForTokenDeltas(actors, before, {
      seller: total - firstPlatform - firstReferrer,
      platform: firstPlatform,
      referrer: firstReferrer,
    });

    const replay = await fetch(`${secondBaseUrl}/api/v1/marketplace/marketplace-dataset/purchase`, {
      method: "POST",
      headers: {
        authorization: paid.authorization,
        "content-type": "application/json",
      },
      body: JSON.stringify({ idempotencyKey: "split-policy" }),
    });
    const body = await optionalJson(replay);
    await delay(1_000);

    expect(replay.status).not.toBe(200);
    expect(body).not.toMatchObject({ ok: true, productId: "marketplace-dataset" });
    expect(await tokenBalances(actors)).toEqual(afterPayment);
  }, 120_000);

  it("rejects conflicting idempotency input without changing settlement state", async () => {
    await assertRpcReady(rpcUrl);
    const actors = await createSplActors(10_000_000n);
    const unitPrice = 1_000_000n;
    await createAssociatedTokenAccount({ payer: actors.payer, mint: actors.mint, owner: actors.seller.address }, rpcUrl);
    const before = await getTokenBalance(actors.seller.address, actors.mint, rpcUrl);
    const baseUrl = await serve(splEnv(actors, { meteredUnitPrice: unitPrice }));
    const session = await postJson(`${baseUrl}/api/v1/sessions`, { accountId: "acct", planId: "metered-api" });

    const paid = await payAndCaptureAuthorization(
      actors.payer,
      `${baseUrl}/api/v1/sessions/${session.sessionId}/settlements`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ units: 3, idempotencyKey: "usage" }),
      },
    );
    await expectConfirmedReceiptTransaction(paid.receipt);
    const afterPayment = await waitForTokenBalanceAtLeast(actors.seller.address, actors.mint, before + 3n * unitPrice, rpcUrl);

    const conflict = await fetch(`${baseUrl}/api/v1/sessions/${session.sessionId}/settlements`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ units: 4, idempotencyKey: "usage" }),
    });
    const currentSession = await (await fetch(`${baseUrl}/api/v1/sessions/${session.sessionId}`)).json();
    await delay(1_000);

    expect(conflict.status).toBe(409);
    expect(currentSession).toMatchObject({ usedUnits: "3" });
    expect(await getTokenBalance(actors.seller.address, actors.mint, rpcUrl)).toBe(afterPayment);
  }, 120_000);

  it("rejects expired and over-limit settlement attempts before fulfillment", async () => {
    await assertRpcReady(rpcUrl);
    const actors = await createSplActors(10_000_000n);
    await createAssociatedTokenAccount({ payer: actors.payer, mint: actors.mint, owner: actors.seller.address }, rpcUrl);
    const before = await getTokenBalance(actors.seller.address, actors.mint, rpcUrl);
    const baseUrl = await serve(splEnv(actors, {
      maxUnits: 2,
      meteredUnitPrice: 1_000_000n,
      sessionTtlSeconds: 1,
    }));
    const expiredSession = await postJson(`${baseUrl}/api/v1/sessions`, { accountId: "acct-expired", planId: "metered-api" });
    await delay(1_200);

    const expired = await createMppClient(actors.payer, rpcUrl).fetch(
      `${baseUrl}/api/v1/sessions/${expiredSession.sessionId}/settlements`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ units: 1, idempotencyKey: "late" }),
      },
    );
    const activeSession = await postJson(`${baseUrl}/api/v1/sessions`, { accountId: "acct-limit", planId: "metered-api" });
    const overLimit = await createMppClient(actors.payer, rpcUrl).fetch(
      `${baseUrl}/api/v1/sessions/${activeSession.sessionId}/settlements`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ units: 3, idempotencyKey: "too-many" }),
      },
    );

    expect(expired.status).toBe(409);
    expect(overLimit.status).toBe(409);
    expect(await (await fetch(`${baseUrl}/api/v1/sessions/${expiredSession.sessionId}`)).json()).toMatchObject({
      state: "expired",
      usedUnits: "0",
    });
    expect(await (await fetch(`${baseUrl}/api/v1/sessions/${activeSession.sessionId}`)).json()).toMatchObject({
      state: "active",
      usedUnits: "0",
    });
    expect(await getTokenBalance(actors.seller.address, actors.mint, rpcUrl)).toBe(before);
  }, 120_000);
});

type CapturedPayment = {
  authorization: string;
  receipt: ReturnType<typeof Receipt.fromResponse>;
  response: Response;
};

type SplActors = {
  payer: TransactionSigner;
  mintAuthority: TransactionSigner;
  mintSigner: TransactionSigner;
  mint: Address;
  seller: TransactionSigner;
  platform: TransactionSigner;
  referrer: TransactionSigner;
};

type SplCatalogAmounts = Partial<{
  premiumAmount: bigint;
  marketplaceAmount: bigint;
  platformSplit: bigint;
  referrerSplit: bigint;
  meteredUnitPrice: bigint;
  renewalAmount: bigint;
  maxUnits: number;
  sessionTtlSeconds: number;
}>;

async function serve(env: NodeJS.ProcessEnv): Promise<string> {
  const server = await startExpressServer(env);
  closeServers.push(server.close);
  return server.baseUrl;
}

async function payAndCaptureAuthorization(
  payer: TransactionSigner,
  url: string,
  init?: RequestInit,
): Promise<CapturedPayment> {
  let authorization: string | undefined;
  const client = createMppClient(payer, rpcUrl);
  client.onCredentialCreated((payload) => {
    authorization = payload.credential;
  });

  const response = await client.fetch(url, init);
  const receipt = Receipt.fromResponse(response);
  expect(receipt).toMatchObject({ method: "solana", status: "success" });
  if (authorization === undefined) throw new Error("Expected client Authorization event");
  return { authorization, receipt, response };
}

async function createSplActors(payerTokens: bigint): Promise<SplActors> {
  const payer = await createSigner();
  const mintAuthority = await createSigner();
  const mintSigner = await createSigner();
  const seller = await createSigner();
  const platform = await createSigner();
  const referrer = await createSigner();

  await airdropAndWait(payer.address, 2_000_000_000n, rpcUrl);
  const mint = await createSplMint({ payer, mintAuthority, mint: mintSigner }, rpcUrl);
  await mintSplTokensToOwner({ payer, mint, mintAuthority, owner: payer.address, amount: payerTokens }, rpcUrl);

  return { payer, mintAuthority, mintSigner, mint, seller, platform, referrer };
}

async function expectConfirmedReceiptTransaction(receipt: ReturnType<typeof Receipt.fromResponse>) {
  const transaction = await waitForTransaction(receipt.reference, rpcUrl);
  expect(transaction.meta?.err ?? null).toBeNull();
  return transaction;
}

function nativeEnv(recipient: Address, amount: bigint): NodeJS.ProcessEnv {
  return {
    PAID_ROUTE_AMOUNT_BASE_UNITS: amount.toString(),
    PAID_ROUTE_CURRENCY: "sol",
    PAID_ROUTE_DESCRIPTION: "Agent report",
    SOLANA_PAYMENT_NETWORK: "localnet",
    SOLANA_PAYMENT_RECIPIENT: recipient,
    SOLANA_RPC_URL: rpcUrl,
    MPP_SECRET_KEY: mppSecret,
    MPP_REALM: realm,
  };
}

function splEnv(actors: SplActors, amounts: SplCatalogAmounts = {}): NodeJS.ProcessEnv {
  const premiumAmount = amounts.premiumAmount ?? 2_500_000n;
  const marketplaceAmount = amounts.marketplaceAmount ?? 10_000_000n;
  const platformSplit = amounts.platformSplit ?? 1_000_000n;
  const referrerSplit = amounts.referrerSplit ?? 500_000n;
  const meteredUnitPrice = amounts.meteredUnitPrice ?? 1_000_000n;
  const renewalAmount = amounts.renewalAmount ?? 12_000_000n;
  const maxUnits = amounts.maxUnits ?? 10;
  const sessionTtlSeconds = amounts.sessionTtlSeconds ?? 3600;

  return {
    PAID_ROUTE_AMOUNT_BASE_UNITS: premiumAmount.toString(),
    PAID_ROUTE_CURRENCY_MINT: actors.mint,
    PAID_ROUTE_DECIMALS: String(splTokenDecimals),
    PAID_ROUTE_DESCRIPTION: "Agent report",
    SOLANA_PAYMENT_NETWORK: "localnet",
    SOLANA_PAYMENT_RECIPIENT: actors.seller.address,
    SOLANA_RPC_URL: rpcUrl,
    MPP_SECRET_KEY: mppSecret,
    MPP_REALM: realm,
    COMMERCE_CATALOG_JSON: JSON.stringify({
      payment: {
        currency: actors.mint,
        decimals: splTokenDecimals,
        network: "localnet",
        rpcUrl,
        secretKey: mppSecret,
        realm,
      },
      premiumProducts: [{
        id: "premium-report",
        amountBaseUnits: premiumAmount.toString(),
        description: "Premium research report",
        recipient: actors.seller.address,
      }],
      marketplaceProducts: [{
        id: "marketplace-dataset",
        amountBaseUnits: marketplaceAmount.toString(),
        description: "Marketplace dataset",
        recipient: actors.seller.address,
        splits: [
          { recipient: actors.platform.address, amount: platformSplit.toString(), memo: "Platform" },
          { recipient: actors.referrer.address, amount: referrerSplit.toString(), memo: "Referrer" },
        ],
      }],
      meteredPlans: [{
        id: "metered-api",
        unitPriceBaseUnits: meteredUnitPrice.toString(),
        maxUnits,
        sessionTtlSeconds,
        paymentExpirySeconds: 300,
        description: "Metered API usage",
        recipient: actors.seller.address,
      }],
      subscriptionPlans: [{
        id: "monthly-api",
        priceBaseUnits: renewalAmount.toString(),
        periodDurationMonths: 1,
        paymentExpirySeconds: 300,
        description: "Monthly API access",
        recipient: actors.seller.address,
      }],
    }),
  };
}

async function postJson(url: string, body: unknown): Promise<Record<string, string>> {
  const response = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  expect(response.status).toBeLessThan(300);
  return response.json() as Promise<Record<string, string>>;
}

async function optionalJson(response: Response): Promise<unknown> {
  const text = await response.text();
  if (text.length === 0) return undefined;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

async function tokenBalances(actors: SplActors) {
  const [seller, platform, referrer] = await Promise.all([
    getTokenBalance(actors.seller.address, actors.mint, rpcUrl),
    getTokenBalance(actors.platform.address, actors.mint, rpcUrl),
    getTokenBalance(actors.referrer.address, actors.mint, rpcUrl),
  ]);
  return { seller, platform, referrer };
}

async function waitForTokenDeltas(
  actors: SplActors,
  before: Awaited<ReturnType<typeof tokenBalances>>,
  expected: Awaited<ReturnType<typeof tokenBalances>>,
) {
  const startedAt = Date.now();
  while (Date.now() - startedAt < 30_000) {
    const current = await tokenBalances(actors);
    if (
      current.seller - before.seller === expected.seller &&
      current.platform - before.platform === expected.platform &&
      current.referrer - before.referrer === expected.referrer
    ) {
      return current;
    }
    await delay(500);
  }
  throw new Error("Timed out waiting for marketplace token deltas");
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
